### ISSUE TITLE
Tory Fighting Animation

### ISSUE THREAD

**Issue by avl27** [pvcraven/2018_cis390ag#166] opened 2018-03-13 23:33 UTC
Use Tory fighting sprite sheet to create fighting animation when Tory attacks

**Comment by wolffcaleb** [comment] 2018-03-22 05:30
Sorry, this is already completed @iamaname2

**Comment by iamaname2** [comment] 2018-03-28 17:17
Duplicate of #127

**Closed by iamaname2** 2018-03-28 17:17 UTC
Labels: 1 Point
