### ISSUE TITLE
Jumping is still pretty broken.

### ISSUE THREAD

**Issue by NanoBytesInc** [pvcraven/2018_cis390ag#314] opened 2018-03-28 17:03 UTC
On the training level, Tory is not able to jump high enough to climb up the first hill, unless the user is simultaneously pressing "left/right"

Jumping without these pressed is broken

**Comment by EliTaue** [comment] 2018-03-30 19:41
Player cannot jump with out moving and sometimes can't jump at all even when moving or using above trick. Player can jump high enough to clear the background trees if going up a hill. Sometimes while jumping up while going up a hill player jumps up off the world.

**Comment by pvcraven** [comment] 2018-04-06 19:43
Duplicate of #306

**Closed** 2018-04-09 19:51 UTC
Labels: bug, duplicate
