### ISSUE TITLE
Tory Running Animation

### ISSUE THREAD

**Issue by avl27** [pvcraven/2018_cis390ag#169] opened 2018-03-13 23:38 UTC
Use Tory running sprite sheet to create animation when Tory runs.

**Comment by braedeningersoll** [comment] 2018-03-14 19:16
I believe this is a duplicate of #98, I worked on one that should be added to the source files and to the Unity project.

**Comment by justinhovey** [comment] 2018-03-21 19:51
I think this card was meant to implement the sprite sheet into Unity. We'll make a new card for the next sprint

**Closed by justinhovey** 2018-03-21 19:51 UTC
Labels: 1 Point
